### ISSUE TITLE
Collector as a side effect ?

### ISSUE THREAD

**Issue by vsraptor** [JulienPalard/Pipe#52]
how would you write a function that acts as collector i.e. because i normally have the source as list or numpy array, but want to collect the result as 2D-bitarray ...f.e.

    np.random.randint(0,100,10)  | ....... | before_last |  list2Dbitary()

in this case before_last  generates numpy-array-of-bitarrays and then in the last step I convert it to 2Dbitarray ... i.e. the pipe generates 2 data structs which can be large and will take too much memory..

If I have something as context/state then as a side effect of functions I can update this 2Dbitarray created before the pipe starts.

How would you do that ?

**Comment by JulienPalard** [comment]
Avoid writing pipe function that are *not* returning a pipable thing, it's ofen more readable:

    list2Dbitary(np.random.randint(0,100,10)  | ....... | before_last)

and allows one to add at the end of the pipe without breaking:

    list2Dbitary(np.random.randint(0,100,10)  | ....... | before_last | one_more_thing)

It makes the protocol clear: pipes gives iterables (pipables), instead of "having half of them returnings "finals" and half of them returning pipable, and having to learn which yields what".

**Comment by vsraptor** [comment]
what about if it is efficiency issue as in my case it takes alot of memory ...

       np.random.randint(0,100,10000000) | ....

I suppose one idea is to do it in batches and then merge them ...  !! put the pipe in a function and call it repeatedly.  
Is there an abstraction for end-of-pipe processing ? I used your passed() fun, but it acts as a sink not a collector ?

**Comment by JulienPalard** [comment]
From an efficiency point of view there can be (if implemented correctly) no difference between:

    foo | bar | baz | final

and

    final(foo | bar | baz)

if in both cases final is consuming the given generator instead of transforming it into a list.

Put in other words, the syntax `final(foo | bar | baz)` does *not* enforces that `foo | bar | baz` is fully computed before giving it to final.

As in:
```python
from pipe import select, where

def final(source):
    print("Starting final")
    total = 0
    for item in source:
        print(f"Final accumulating {item}")
        total += item
    return total

def source():
    print("Starting source")
    for i in range(10, 21):
        print(f"Source yielding {i}")
        i += 10
        yield i


print(final(source() | select(lambda x: x ** 2) | where(lambda x: x > 500)))
```
Printing:
```
Starting final
Starting source
Source yielding 10
Source yielding 11
Source yielding 12
Source yielding 13
Final accumulating 529
Source yielding 14
Final accumulating 576
Source yielding 15
Final accumulating 625
Source yielding 16
Final accumulating 676
Source yielding 17
Final accumulating 729
Source yielding 18
Final accumulating 784
Source yielding 19
Final accumulating 841
Source yielding 20
Final accumulating 900
5660
```

Notice how final and source are coworking, even with the `select` and the `where` in between.

**Comment by vsraptor** [comment]
i see thanks ... makes sense ;)
