### ISSUE TITLE
undocumented pipes?

### ISSUE THREAD

**Issue by jerabaul29** [JulienPalard/Pipe#75]
Looks like there are some undocumented pipes; see for example netcat in https://github.com/JulienPalard/Pipe/blob/master/pipe.py (in addition to the deprecated closing pipes, but I guess not documenting these is the whole point :) ).

**Comment by JulienPalard** [comment]
`netcat` is not a closing pipe as it yields the socket response, so it should be usable as a command-line netcat.

But looks like I implemented in around 2010 in Python 2, a time where strings were bytes, the function may no longer work (due to the `| traverse` yielding integers).

By removing `| traverse` it works:
```
for line in [
    b"GET / HTTP/1.1\r\n",
    b"Host: python.org\r\n",
    b"Connection: close\r\n",
    b"\r\n",
] | netcat("python.org", 80):
    print(line)
```

gives:

```text
b'HTTP/1.1 301 Moved Permanently\r\nContent-length: 0\r\nLocation: https://python.org/\r\nConnection: close\r\n\r\n'
```

I think it would be better if the `netcat` pipe were line-oriented instead of block oriented (in its yields), because it's probably how users would think of it, as it's really remeniscent of command line.

I'm tempted to fix it and move it to the README as an example, as IIRC I did it just to tell "You can implement many things with @Pipe, don't lock your mind with integers sequences". (Moving it can be done without marking it as deprecated as it was neither documented nor working in Python 3). What do you think?

**Comment by jerabaul29** [comment]
Yes, I was not meaning that netcat was a closing pipe, just that netcat is not documented, while looking like a perfectly fine pipe, and that in addition to netcat, a number of depreciated closing pipes are also not documented, but that is probably the point for this later category :) . Sorry if this was not clear.

Having a working netcat and in the documentation sounds good to me.

**Comment by JulienPalard** [comment]
Added a netcat example in the README and added a test for it.

Thanks for the issue!
